// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoHHecddNzDHTq5aNVfUPQHXiDL8wuld0',
    appId: '1:913117661475:web:42f49974aa6b247fe16496',
    messagingSenderId: '913117661475',
    projectId: 'insightify-eea23',
    authDomain: 'insightify-eea23.firebaseapp.com',
    storageBucket: 'insightify-eea23.appspot.com',
    measurementId: 'G-SW9CS81GXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6re-m3-ThSe2J-y1cxrI4GzjV1VHmwMU',
    appId: '1:913117661475:android:0632f4497b463de9e16496',
    messagingSenderId: '913117661475',
    projectId: 'insightify-eea23',
    storageBucket: 'insightify-eea23.appspot.com',
  );

}